//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Controller
{
    using System;
    using System.Collections.Generic;
    
    public partial class Booking
    {
        public Booking()
        {
            this.Ticktes = new HashSet<Tickte>();
        }
    
        public int idBooking { get; set; }
        public int idDeparture { get; set; }
        public string idUser { get; set; }
        public System.DateTime bookingDate { get; set; }
        public string bookingStatus { get; set; }
        public decimal totalPrice { get; set; }
    
        public virtual Departure Departure { get; set; }
        public virtual User User { get; set; }
        public virtual ICollection<Tickte> Ticktes { get; set; }
    }
}
