//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Controller
{
    using System;
    using System.Collections.Generic;
    
    public partial class Booking
    {
        public int idBooking { get; set; }
        public int idDeparture { get; set; }
        public string idUser { get; set; }
        public string passportNo { get; set; }
        public string bookingStatus { get; set; }
        public System.DateTime bookingDate { get; set; }
        public System.DateTime departureDate { get; set; }
        public decimal bookPrice { get; set; }
    
        public virtual Departure Departure { get; set; }
        public virtual Passenger Passenger { get; set; }
    }
}
