//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Controller
{
    using System;
    using System.Collections.Generic;
    
    public partial class Departure
    {
        public Departure()
        {
            this.Bookings = new HashSet<Booking>();
        }
    
        public int idDeparture { get; set; }
        public string idFlight { get; set; }
        public System.DateTime startDate { get; set; }
        public System.DateTime endDate { get; set; }
        public int vacancy { get; set; }
    
        public virtual ICollection<Booking> Bookings { get; set; }
        public virtual Flight Flight { get; set; }
    }
}
