//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Controller
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tickte
    {
        public int idTicket { get; set; }
        public int idBooking { get; set; }
        public string passportNo { get; set; }
        public decimal ticketPrice { get; set; }
    
        public virtual Booking Booking { get; set; }
    }
}
