//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Controller
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        public User()
        {
            this.Passengers = new HashSet<Passenger>();
        }
    
        public string idUser { get; set; }
        public string password { get; set; }
        public string phoneNo { get; set; }
        public string status { get; set; }
        public string idRole { get; set; }
    
        public virtual ICollection<Passenger> Passengers { get; set; }
        public virtual Role Role { get; set; }
    }
}
